name: musie
description: Musie Flutter Client
publish_to: 'none'
version: 0.1.3+20

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  auto_route: 7.8.0
  cocoicons: ^0.1.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  flex_color_scheme: ^7.2.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.10
  google_fonts: ^5.1.0
  intl: any
  just_audio: ^0.9.34
  loggy: ^2.0.3
  on_audio_query: ^2.9.0
  package_info_plus: ^4.1.0
  sentry_flutter: ^7.9.0
  shared_preferences: ^2.2.1

dev_dependencies:
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  flutter_lints: ^2.0.2
  sentry_dart_plugin: ^1.5.0

flutter:
  generate: true
  assets:
    - shorebird.yaml
    - assets/images/
  uses-material-design: true

sentry:
  upload_debug_symbols: true
  upload_source_maps: false
  upload_sources: false
  wait_for_processing: false
  log_level: error
  commits: auto
  ignore_missing: true
