name: musie
description: Musie Flutter Client
publish_to: 'none'
version: 0.1.2

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  assets:
    - shorebird.yaml
  uses-material-design: true
