name: musie
description: Musie Flutter Client
publish_to: 'none'
version: 0.1.3+18

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  loggy: ^2.0.3
  package_info_plus: ^4.0.2
  sentry_flutter: ^7.9.0

dev_dependencies:
  flutter_lints: ^2.0.0
  sentry_dart_plugin: ^1.5.0

flutter:
  assets:
    - shorebird.yaml
    - assets/images/
  uses-material-design: true

sentry:
  upload_debug_symbols: true
  upload_source_maps: false
  upload_sources: false
  wait_for_processing: false
  log_level: error
  commits: auto
  ignore_missing: true
