name: CI
on:
    - pull_request
    - workflow_dispatch

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    analyze:
        timeout-minutes: 15
        name: Analyze Code Base
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Branch
              uses: actions/checkout@v3
              with:
                token: ${{ secrets.GITHUB_TOKEN }}

            - name: Setup Flutter SDK
              uses: subosito/flutter-action@v2
              with:
                flutter-version: 3.10.6

            - run: flutter --version

            - name: Install Flutter Dependencies
              run: flutter pub get

            - name: Analyze Project Source
              run: flutter analyze --no-fatal-infos

            - name: Format dart files with 80 line length
              run: find . -type f -name '*.dart' ! -name '*.g.dart' ! -name '*app_localizations*.dart' ! -name '*.mocks.dart' -print0 | xargs dart format . --line-length 80 --output=none --set-exit-if-changed

            - name: Format generated dart files with 80 chars
              run: find . -type f -name '*.g.dart' ! -name '*.mocks.dart' -print0 | xargs dart format . --output=none --set-exit-if-changed
